---
- name: Launch Kubernetes Job in Minikube
  hosts: localhost
  tasks:
    - name: Set KUBECONFIG environment variable
      ansible.builtin.set_env:
        KUBECONFIG: /home/ubuntu/.kube/config
    - name: Create Kubernetes Job
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: syft
            namespace: default
          spec:    # Moved `spec` here
            template:
              metadata:
                labels:
                  app: syft
              spec:
                containers:
                  - name: syft
                    image: anchore/syft:latest
                    args:
                      - alpine
                      - -o cyclonedx-json
                restartPolicy: Never
